### ISSUE TITLE
Seems like "man" is missing from "gals-men"

### ISSUE THREAD

**Issue by eddiejaoude** [retextjs/retext-equality#105]
### Subject of the issue

Seems like `man` is missing from `gals-men`, `woman` is picked up, but `man` is not.

### Your environment

*   **OS**: Mac 11.1
*   **Packages**: 
*   **Env**: node v15.5

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

- woman -> flagged
- man -> flagged

<img width="691" alt="Screenshot 2021-01-07 at 10 45 15" src="https://user-images.githubusercontent.com/624760/103883689-75d3c100-50d5-11eb-8e55-eacd918d2f42.png">

<img width="1058" alt="Screenshot 2021-01-07 at 10 28 36" src="https://user-images.githubusercontent.com/624760/103884213-2641c500-50d6-11eb-9f7c-305ade19dbd5.png">

### Actual behavior

- woman -> flagged
- man -> not flagged

**Comment by Utkarsh299-tech** [comment]
Hey @eddiejaoude, can I work on this issue?

**Comment by eddiejaoude** [comment]
@Utkarsh299-tech sure 👍 that would be awesome!! Thank you 🤓

**Comment by Utkarsh299-tech** [comment]
> @Utkarsh299-tech sure 👍 that would be awesome!! Thank you 🤓

Hey, I've created the PR. Hoping everything to be fine. And thank you!😃

**Comment by eddiejaoude** [comment]
It looks like you have updated the documentation but not the config?

I think more changes will have to go in the config file https://github.com/retextjs/retext-equality/blob/main/data/en/gender.yml

**Comment by Utkarsh299-tech** [comment]
> It looks like you have updated the documentation but not the config?
> 
> I think more changes will have to go in the config file https://github.com/retextjs/retext-equality/blob/main/data/en/gender.yml

Thank you so much @eddiejaoude! I did the required changes to the config file.

**Comment by eddiejaoude** [comment]
Great 👍 . Looking forward to these improvements. PR is here for context for anyone else reading https://github.com/retextjs/retext-equality/pull/106
