### ISSUE TITLE
Suggest `spree`,  (?) instead of `binge`

### ISSUE THREAD

**Issue by wooorm** [retextjs/retext-equality#110]
### Subject of the feature

Suggest `spree`, other things (?) instead of `binge`

### Problem

`binge` might be insensitive towards folks with eating disorders

### Expected behavior

🤷‍♂️

---

Suggested over email

**Comment by smokris** [comment]
> `binge` might be insensitive towards folks with eating disorders

Yeah, or alcoholism.

> Suggest `spree`

Also `enthusiastic` and many of its synonyms (passionate, intense, dedicated, determined, eager, avid, keen, fierce, ardent, wholehearted, freewheeling, unbridled) are more positive, and could be used in place of `binge` in many contexts.

"I was on a thesaurus binge." -> "I ardently rummaged through a thesaurus."

**Comment by wooorm** [comment]
Thanks @smokris for the great suggestion!
