### ISSUE TITLE
Add support for "Cracker"

### ISSUE THREAD

**Issue by dannybrown** [retextjs/retext-equality#118]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

This project does not include racially insensitive words for white people.

### Solution

Add the word "Cracker" as an offensive word.

### Alternatives

Acknowledge that this is an incomplete project if you work in countries with a white-minority population on the README.md

**Comment by wooorm** [comment]
`retext-profanities`

**Comment by danny-brownCF** [comment]
Any reason?

**Comment by wooorm** [comment]
Read my comment. It’s already there.

**Comment by Murderlon** [comment]
Context:`retext-equality` is used for language that could be inconsiderate but is not necessarily considered profane. [`retext-profanities`](https://github.com/retextjs/retext-profanities) is used for profanities, which is where you suggestion would fit better.

**Comment by wooorm** [comment]
And already is...

**Comment by dannybrown** [comment]
I don't understand how `sand nigger` is different to `cracker`. To the extent they would be in different projects.

Both are racial epithets -- Can you explain this to me?

I'm also not sure that the tonality of "of course we have considered this word and objectively determined its offensiveness level" is useful.
