### ISSUE TITLE
All racial epithets should be equal

### ISSUE THREAD

**Issue by dannybrown** [retextjs/retext-equality#119]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

No one person can belong to all racial groups.

This means that no one person can objectively determine how offensive a word is. 

Tier ranking how offensive one racial epithet over another seems like a slippery slope to the type of problem this project purports to be trying to solve

### Solution

All racial epithets should be in this package. They're an equality issue, not a profanity issue. They should all be considered at the same level and as one evil.

### Alternatives

Write supporting documentation which details the thought process behind the tier ranking of each racial epithet. I suspect this won't be pretty.

**Comment by Murderlon** [comment]
This issue is vague and not actionable, hence it can't be solved. Consider defining what these so called missing racial epithets are, and proposing that specifically.

**Comment by dannybrown** [comment]
> This issue is vague and not actionable, hence it can't be solved. Consider defining what these so called missing racial epithets are, and proposing that specifically.

I did, that issue was closed as well.

Can you please be consistent?

**Comment by wooorm** [comment]
Slurs go in a different project: `retext-profanities`. That project’s ranking is not related to how profane those words are.
