### ISSUE TITLE
Add support for "Cracker"

### ISSUE THREAD

**Issue by dannybrown** [retextjs/retext-equality#120]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

@Murderlon has asked me to re-open this issue as it covers a specific term that can be rectified. He outlines his reasoning for this in #119.

No one person can belong to all racial groups.

This means that no one person can objectively determine how offensive a word is.

Tier ranking how offensive one racial epithet over another seems like a slippery slope to the type of problem this project purports to be trying to solve.

If `sand nigger` is appropriate here, so is `cracker`. 

Without making a judgement on the validity of peoples hurt feelings we cannot come up with a reason for why one is here and another isn't.

### Solution

Add `cracker` to this repo

### Alternatives

Remove `sand nigger` from this repo

**Comment by Murderlon** [comment]
Hi, "cracker" does already exist in `retext-profanities`: https://github.com/retextjs/retext-profanities/blob/main/rules.md. I suppose it's a bit of a thin line between that package and this one. I'm not sure if they can be in both, as tools like `alex` use both packages, which may give the same warnings twice. So at the end of the day we pick one, not both for this to be in. As it's already in `retext-profanities` I think we can keep things as as.

**Comment by dannybrown** [comment]
> Hi, "cracker" does already exist in `retext-profanities`: https://github.com/retextjs/retext-profanities/blob/main/rules.md. I suppose it's a bit of a thin line between that package and this one. I'm not sure if they can be in both, as tools like `alex` use both packages, which may give the same warnings twice. So at the end of the day we pick one, not both for this to be in. As it's already in `retext-profanities` I think we can keep things as as.

Fine, I'll make a PR to remove sand niggers then
