### ISSUE TITLE
Accept the responsibility associated with your work

### ISSUE THREAD

**Issue by dannybrown** [retextjs/retext-equality#122]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I have followed each of @Murderlon's suggestions whilst trying to contribute to this project.

This project is downloaded by 20,000 people a week who are actively working to try and improve their use of language.

This project, according to @Murderlons comment in #118, contains only words which are "inconsiderate but is not necessarily considered profane"

This project considers "sand niggers" to be a lesser insult than "cracker" by including it only in this project and not in the profanities project. 

The use of the phrase "sand niggers" is explicitly illegal in the United Kingdom and would therefore clearly be better suited to the profanity project. This is also true of the other racial epithets in this project.

@Murderlon has said that his rationale for this is so obvious that he doesn't have to explain it. Given the illegality of the words used in this project I cannot see that it is that obvious. 

One might also think that if the true aim of this project was to improve the language used by people who download it then a discussion (not the immediate closure of issues) followed by an explanation might move not only the project, but the aims of the project as a whole, in the right direction.

I would like to invite @Murderlon to join a call with me and some friends from the Muslim Council of Britain to see if we can correct his thinking.

### Solution

Accept responsibility

### Alternatives

Acknowledge failure

**Comment by Murderlon** [comment]
> This project, according to @Murderlons comment in #118, contains only words which are "inconsiderate but is not necessarily considered profane"

to be more precise: this project is for language targeting minority groups and language that could someone in general feel targeted

> This project considers "sand niggers" to be a lesser insult than "cracker" by including it only in this project and not in the profanities project.

it does not, "sand niggers" targets Arab people, the key thing is the "sand" in that composition. Which makes it part of this project. The actual N is what is illegal, and you can find that already in the profanities project

> @Murderlon has said that his rationale for this is so obvious that he doesn't have to explain it

You created a PR that removed good progress on this project because your suggestion wasn't immediately accepted. Think about it. 


> One might also think that if the true aim of this project was to improve the language used by people who download it then a discussion (not the immediate closure of issues) followed by an explanation might move not only the project, but the aims of the project as a whole, in the right direction.

You are right in this regard.

**Comment by dannybrown** [comment]
> > This project, according to @Murderlons comment in #118, contains only words which are "inconsiderate but is not necessarily considered profane"
> 
> to be more precise: this project is for language targeting minority groups and language that could someone in general feel targeted
> 
> > This project considers "sand niggers" to be a lesser insult than "cracker" by including it only in this project and not in the profanities project.
> 
> it does not, "sand niggers" targets Arab people, the key thing is the "sand" in that composition. Which makes it part of this project. The actual N is what is illegal, and you can find that already in the profanities project
> 
> > @Murderlon has said that his rationale for this is so obvious that he doesn't have to explain it
> 
> You created a PR that removed good progress on this project because your suggestion wasn't immediately accepted. Think about it.
> 
> > One might also think that if the true aim of this project was to improve the language used by people who download it then a discussion (not the immediate closure of issues) followed by an explanation might move not only the project, but the aims of the project as a whole, in the right direction.
> 
> You are right in this regard.

I'm sorry you are just wrong about the law.

**Comment by dannybrown** [comment]
I created a PR that did exactly what you asked me to

**Comment by dannybrown** [comment]
Considering your background, and your inability to receive any form of constructive criticism, is it right that you have this much power @Murderlon ?

**Comment by wooorm** [comment]
> This project considers `s*nd n*****s` to be a lesser insult than "cracker" by including it only in this project and not in the profanities project.

This statement is incorrect. Both are in `retext-profanities`. Only the former was here. I removed it.

> a discussion (not the immediate closure of issues)

Not every person on the internet comes here with the best of intent.
Nobody “deserves” a discussion.
What you “deserve” is explained in the license: https://github.com/retextjs/retext-equality/blob/main/license:

```
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
```

From your barrage of issues and the way you attack people, I don’t think you’re serious about improving anything.
