### ISSUE TITLE
Get non-software engineers to help

### ISSUE THREAD

**Issue by dannybrown** [retextjs/retext-equality#123]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

In #122 @Murderlon makes the suggestion that anti-arab racism is not illegal in and of itself in the United Kingdom. "Sand nigger" is not dealt with as the concatenation of the word "sand" with an actual offensive term. It is an offensive term that has legal consequences all of it's own.

If the legality of a word determines which repo it sits within then this project should retain legal counsel in each country it intends to support -- if only to ensure the package is accurate. 

@Murderlon, a software engineer, is not a lawyer and is making decisions that make absolutely zero logical sense in this regard.

Despite acknowledging that this project should accept input, discuss it, and try to move towards better language for all he then immediately closes the issue.

The level of effort being put in to stop insults towards Arabs being treated the same as insults towards white people is concerning. Thusly, I have reported this project to both `npm` and `GitHub` for violating community guidelines.

This entire mess is a really good example of why this project perhaps doesn't make sense at all. 

### Solution

* Retain counsel in every country this project aims to support if you're making decisions based on legality. Software engineers are _NOT_ lawyers.

* Stop running the project. Inaccuracies on the issue of racism are worse than the project not existing at all. This could very easily result in an increase in using of "sand niggers" as it is a lesser problem according to the linter... almost making it acceptable to _some_ people, much like a compiler warning vs an error.

* Discuss things in issues, don't just close them

### Alternatives

Acknowledge that the issues this repo attempts to solve are socio-cultural.

Acknowledge that software engineers are famously not the right people to solve socio-cultural problems. 

Acknowledge that people who cannot accept constructive criticism on socio-cultural issues should not be running projects which aim to improve socio-cultural problems.

**Comment by wooorm** [comment]
> illegal

You keep on hammering about this. This project does not concern itself with what is legal or not in regions.

> non-software engineers

People who are not software engineers are welcome to help.
See `contibuting.md` for more information on how to help: https://github.com/retextjs/retext-equality#contributing.

> Acknowledge that the issues this repo attempts to solve are socio-cultural.
>
> Acknowledge that software engineers are famously not the right people to solve socio-cultural problems.

Sure, both are correct. It does not mean that software engineers should not attempt to solve problems. So I disagree with the third point.
