### ISSUE TITLE
German Language Support

### ISSUE THREAD

**Issue by jokroese** [retextjs/retext-equality#125]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am supporting a colleague's project to build a browser plugin for encouraging gender-neutral language in German. I was really happy to find `retext-equality` and think it could be a brilliant base for some of the functionality.

I want to support my colleague in adding German language to `retext-equality`. (Some of the contributors won't be familiar with programming and I don't speak German.) I have seen that there are similar approaches to support `retext-profanities` (https://github.com/get-alex/alex/issues/212). I also found a relevant issue here which ended with @wooorm refactoring the code to support multiple languages (https://github.com/retextjs/retext-equality/issues/59). This is great!

I've started following the suggestions in https://github.com/retextjs/retext-equality/issues/59#issuecomment-499902610 by adding a couple of basic rules and I am now trying to add the tests. I have a few questions about the best way to do this as it will form the template for both German and adding other languages.

### Solution

1. Should I follow the approach taken in `retext-profanities` and export `retextEqualityDe` from `de.js`?

2. How should I set up tests?

I'm not super familiar with writing tests in Javascript but it looks simple enough. That said, I would like some support in creating a template for testing non-English language patterns in `retext-equality`.

The main reference I have found is that `retext-profanities` has the following test (https://github.com/retextjs/retext-profanities/blob/main/test.js#L35):

```js
const fileFr = await retext().use(retextProfanitiesFrench).process('Merde!')

  assert.deepEqual(
    fileFr.messages.map(String),
    ['1:1-1:6: Don’t use `Merde`, it’s profane'],
    'should support other languages'
  )
```

This only runs for one test, whereas in `retext-equality` there are many tests for English.

Could someone give me an example of how a good template for the non-English tests would look?

### Alternatives

I could intuitively push forward or not put in tests but I don't think either are good ideas!

**Comment by wooorm** [comment]
Hi Joe!

When you add patterns in `data/de/*`, the scripts should do the rest. See https://github.com/retextjs/retext-equality/blob/main/script/generate.js. Run `npm test` to check everything.
So that should do Q1.

For Q2, maybe free make a PR with the data, then I can advise a test for that? Though, what you have for french in retext-profanities, is very similar to what I’d suggest. You don’t have to be exhaustive, a couple of tests should be enough!

**Comment by wooorm** [comment]
Closing for now: translations are welcome — a tracking issue for german in particular is not needed (discussions are a good place for anyone who wants to do the work)
