### ISSUE TITLE
Add explanatory note to 'sophisticated technology'

### ISSUE THREAD

**Issue by rillig** [retextjs/retext-equality#127]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The term 'sophisticated technology' describes advanced technology. As a person not deeply involved into sensitive language, I don't know what's wrong about that term, as it doesn't describe a group of people but rather technical things like machines or inventions.

### Solution

Could you perhaps add an explanation to that entry in `race.yml`, so that I can make an informed decision whether using the word 'sophisticated' is OK in a certain context? At least, https://en.wiktionary.org/wiki/sophisticated#English doesn't generally describe the word as discouraged, it lists an obsolete meaning that might have caused this word to appear in the list of racial words.

### Alternatives

Leave the users (especially nonnative speakers who may only know the primary meaning of the word) unclear about the decision to include the word in the list of racial words.

**Comment by wooorm** [comment]
Hi!

> The term `sophisticated technology` describes advanced technology.

Then you can also use that, `advanced technology`.
The connotation of `sophisticated` with better, cultured, groups, compared to worse groups, is not needed when talking about complex/advanced technology.

> Could you perhaps add an explanation to that entry in `race.yml`

That’s included already, the note explains the pattern:

https://github.com/retextjs/retext-equality/blob/6c71a880135aa254a9674e678c01ced89087a038/data/en/race.yml#L350

> At least, https://en.wiktionary.org/wiki/sophisticated#English doesn't generally describe the word as discouraged, it lists an obsolete meaning that might have caused this word to appear in the list of racial words.

I disagree. It describes words relating to better humans. Or things that appeal to better humans.

---

If you want to add more notes, or more alternatives, PRs are welcome.
If you disagree with a rule, you can always ignore rules. You’re the human: you know better!

Hope this answers your question.

**Comment by rillig** [comment]
When you redard it as acceptable to use the term `sophisticated technology`, why is that exact term listed in `race.yml`?

You wrote:
> That’s included already, the note explains the pattern:
> 
> https://github.com/retextjs/retext-equality/blob/6c71a880135aa254a9674e678c01ced89087a038/data/en/race.yml#L350

I don't understand that explanation, maybe I'm missing some context, or my English is not good enough. I simply don't get the connection how the words "sophisticated technology" might relate to "make some groups sound inferior". Is that connection so common knowledge that there is no need to explain it in the explanation?
