### ISSUE TITLE
Feature request/PR offer - political slogan

### ISSUE THREAD

**Issue by jenweber** [retextjs/retext-equality#41]
Hi! Is it within the scope of this package to include screening for phrases similar to "make America great again," which is a political slogan? It is problematic to many groups that this library tries to help prevent insensitive language towards. Unfortunately it shows up in a lot of things as a joke, since it's an easy play on words, but it's pretty hurtful to some people. Sources: [one](http://dailycampus.com/stories/2017/10/10/dont-normalize-make-america-great-again) and [two](https://www.voanews.com/a/is-make-america-great-racist/4009714.html)

Thoughts? Ideally something like this would be a regex-type match of anything like "make ___ great again" but I don't see that kind of match in any of the other examples. Possibly checking for "great again" would be enough. I haven't thought of any false positives that don't sound like a reference to the phrase.

I am happy to PR this if you think it's within scope and agree that "great again" is a reasonable search term. Thank you!

**Comment by wooorm** [comment]
Oh I totally agree. It should be added here!

* indeed, not sure how a “wildcard” would work. We could add support for those (`make * great again`, where `*` would match any word)
* we could “misuse” [_and_ patterns](https://github.com/retextjs/retext-equality/blob/cab42e40f263a653a0d1aa928cd7fab3acc2ebff/script/race.yml#L1-L19) though, it will search for `make` and `great again` per paragraph?
* Or we could just stay with the default simple pattern for `great again`.

**Comment by wooorm** [comment]
@jenweber I added support for [wildcards in the underlying search mechanism](https://github.com/syntax-tree/nlcst-search/commit/6cabeaad79dd4f4e34cf255291406dd51bdecc15), so `make * great again` (option 1) should work!

**Comment by wooorm** [comment]
Thanks! But I'm mostly horrible at being on time in OSS!
Anyway, let me know if you have questions regarding this project and how it works!
