### ISSUE TITLE
Add more ableist terms

### ISSUE THREAD

**Issue by missmatsuko** [retextjs/retext-equality#44]
Some additions from this list that I didn't see in the rules. Sorry if I missed any!
https://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

- Diffability
- Differently abled or different abilities
- Handicapable
- Special/Special Needs/Specially Abled
- Invalid
- Manic
- Mental/Mental Case
- Midget (existing, but add "little people" as an OK alternative)
- *tard (examples: libtard, fucktard, etc.)
- Short-bus

**Comment by missmatsuko** [comment]
@wooorm Sure, that would be awesome thanks!

**Comment by wooorm** [comment]
Oh apparently if you sign up for hacktoberfest you don’t need the labels on issues, you just need to land 5 PRs.
Thanks for working on this 👍

**Comment by hrb56** [comment]
@missmatsuko I would add stupid, idiot, etc. There's a resource from this website that has a bunch of ableist slurs: https://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

**Comment by missmatsuko** [comment]
Thanks @hrb56 I think those are already included
