### ISSUE TITLE
Add condescending terms (e.g. "obviously")

### ISSUE THREAD

**Issue by missmatsuko** [retextjs/retext-equality#45]
Not sure if it belongs in this retext, but I find that terms like "obviously" and "everyone knows" to be insensitive and inconsiderate.

Couple more ideas here:
https://css-tricks.com/words-avoid-educational-writing/

**Comment by wooorm** [comment]
Nice! This looks a bit like https://github.com/retextjs/retext-passive or https://github.com/retextjs/retext-intensify. Maybe they could go into alex, but they’re also a bit different, not really about “insensitive writing”. I get it’s sort-of relating, but I dunno 🤔
Also not sure if you’re coming from alex, and want it in alex btw. Or just as a retext plugin, because if the latter, then definitely! 👍

**Comment by missmatsuko** [comment]
Hey @wooorm 

I thought it might fit in with retext-equality because this phrasing makes assumptions about the reader's prior experience and cognitive abilities.

I think it doesn't belong in retext-passive because that's checking specifically for passive voice in grammar. 

Maybe it fits in better with retext-simplify or retext-intensify? I'm not really sure.

I did find this repo from Alex. It looks like Alex includes retext-equality and retext-profanities, but does it have its own rules this could go into as well?

**Comment by wooorm** [comment]
Alright! So I checked `retext-intensify` and it includes a few of these.  Most of the words from the list are in [`words/hedges`](https://github.com/words/hedges), `so` is in [`words/fillers`](https://github.com/words/fillers), which leaves `of course`, `everyone knows`, `however`, and `easy`.

> I did find this repo from Alex. It looks like Alex includes retext-equality and retext-profanities, but does it have its own rules this could go into as well?

* We could either add these other cases in one of the underlying word lists for `retext-intensify`, and redirect people there, as I don’t think the whole of `retext-intensify` makes sense inside alex
* Or we could do something like `retext-beginner-friendly` (or maybe `retext-condescending`), with these cases, and use that in alex?

**Comment by missmatsuko** [comment]
Ooh, thanks for looking into that!

I did some thinking on it. I feel like there aren't enough related terms to make up a whole plugin, and I think it also doesn't really fit in with retext-intensify even some of the terms do overlap because the motivations are different (and maybe actually kind of opposing)?

I think it does fit in better with retext-equality based on its description, "
Warn about possible insensitive, inconsiderate language". It's not strictly related to "equality" maybe, or gender/sex/race/disability like most of the existing terms are, but I think it is related. 

For example, if someone uses terms like "obviously" or "everyone can/knows/does", I think there should be a warning to check if they're making assumptions about the reader's privilege and (dis)abilities.

e.g.
"Everyone can do the can-can."
Assumes the reader has the mobility, energy, and coordination to do a physically demanding dance

"Simply print out this form and fill it out in blue ink."
Assumes the reader has access to a printer and can easily fill out a paper form.

**Comment by wooorm** [comment]
OK, let’s try it out! This is exciting!
Could you create a new [YAML](https://github.com/retextjs/retext-equality/tree/master/script) file, `condescending.yml` or so, and try adding some of these?
Maybe we need to do some stuff with the messages though 🤔
