### ISSUE TITLE
Adding notes for some LGBTQ stuff

### ISSUE THREAD

**Issue by wuz** [retextjs/retext-equality#60]
Hey there! I am working on adding some notes for LGBTQ+ terms (and one ablist note) and I had two questions. 

1. Do I need to add notes to the tests somewhere?

2. In this test, if I am changing the note to be an actual description, does this test need to be replicated somewhere else?

```js
t.same(
    retext()
      .use(equality)
      .processSync(doc).messages[0].note,
    'If possible, describe exacly what this is. (source: http://ncdj.org/style-guide/)',
    'should patch `description` when applicable'
  )
```

Once I get some answers and have committed a few rules/notes, I'd love to help get a document set up about contributing, if that would be helpful!

Thanks!

**Comment by wooorm** [comment]
Hey @wuz! #61 is fine! I don’t believe we’re testing notes yet, that could be something to add in the future though.

Also: more docs are more better! Thank you!

**Comment by wooorm** [comment]
I’ll close this here, let’s discuss further on #61!
