### ISSUE TITLE
"null" erroneously considered insensitive

### ISSUE THREAD

**Issue by K900** [retextjs/retext-equality#69]
The word list at https://github.com/retextjs/retext-equality/blob/master/script/press.yml contains an extra empty entry at the very last line, that is converted to `null` during parsing, and then to the string `"null"` somewhere further down the pipeline, leading to the word "null" being considered insensitive. 

via https://www.reddit.com/r/ProgrammerHumor/comments/a7fg4r/html_linter_concerned_about_offensive_language/

**Comment by K900** [comment]
Also, though this probably deserves a separate issue, the capitalization of "Islam" and "Islamic" is inconsistent in the suggestions there - it's title case in one option and lower case in the others. I believe the rule is to always capitalize names of religions, and the Wikipedia Style Guide agrees here: https://en.wikipedia.org/wiki/index.php?title=MOS:ISMCAPS

**Comment by wooorm** [comment]
Hey nice find! As you’ve found the root of the first issue, would you be into creating a PR to remove it (potentially with a test to make sure it doesn’t happen again?).
And same goes for the second, good find!

**Comment by K900** [comment]
I don't really have time to dig into it right now, sorry :( I'd be up to do it after the holidays, but it's totally fine if you or someone else beats me to it :)
