### ISSUE TITLE
Add 'primitive', 'savage', 'sophisticated', 'tribe', 'tribal', 'stone age'

### ISSUE THREAD

**Issue by benmarwick** [retextjs/retext-equality#70]
These terms are considered by professional Anthropologists to be racially charged, derogatory and harmful to the welfare of indigenous groups. The Association of Social Anthropologists issued a [statement](https://www.washingtontimes.com/news/2007/mar/7/20070307-104921-2335r/) that reads:

> 'All anthropologists would agree that the negative use of the terms 'primitive' and 'Stone Age' to describe [indigenous peoples] has serious implications for their welfare. Governments and other social groups. . . have long used these ideas as a pretext for depriving such peoples of land and other resources.'

Similarly, a major NGO dedicated to supporting endangered indigenous groups, [Survival International ](https://www.survivalinternational.org/stampitout.php) writes:

>Terms like 'stone age' and 'primitive' have been used to describe tribal people since the colonial era, reinforcing the idea that they have not changed over time and that they are backward. This idea is both incorrect and very dangerous. It is incorrect because all societies adapt and change, and it is dangerous because it is often used to justify the persecution or forced 'development' of tribal peoples. The results are almost always catastrophic: poverty, alcoholism, prostitution, disease and death.

Could it be something like these, below? 

```
- type: simple
  note: Replace racist language about indigenous peoples with more accurate and inclusive words
  considerate:
    - simple
    - indigenous
    - hunter-gatherer
  inconsiderate:
    - primitive
    - savage
    - stone age
```

```
- type: simple
  note: Replace racist language about indigenous peoples with more accurate and inclusive words
  considerate:
    - society
    - community
  inconsiderate:
    - tribe
```

I'm not sure about this next one, is this a good way to do it?

```
- type: simple
  note: Replace racist language about indigenous peoples with more accurate and inclusive words
  considerate:
    - complex culture
    - complex technology
  inconsiderate:
    - sophisticated culture
    - sophisticated technology
```

What do you think?

**Comment by wooorm** [comment]
Hey nice additions! 👍 Thank you!

I think the note is a bit harsh and doesn’t add much. [`lgbtq.yml`](https://github.com/retextjs/retext-equality/blob/8460c81d48f99120420da81f43d9fb703d667193/script/lgbtq.yml#L3) has some good notes. I think in general those examples are more like the quotes you included in this issue, and I think that’s good.

For your third example, I suggest splitting it up into two patterns, one for culture and one for technology!

**Comment by wooorm** [comment]
@benmarwick Great! 👍 Interested in creating a PR for these changes?

**Comment by benmarwick** [comment]
Thanks for your feedback! Yes, the PR is at https://github.com/retextjs/retext-equality/pull/74
