### ISSUE TITLE
Bug with missing module

### ISSUE THREAD

**Issue by dtmckinney** [retextjs/retext-equality#79]
Hi team, I've been using your repo, it's great. But with the latest release of 3.9.0 I'm getting an npm error now (see error below). It looks like index.js in lib still requires it, but the patterns.json file no longer exists.

`Error: Cannot find module './patterns.json'`

I'd like to continue to use this, so hopefully you can fix this issue soon :)

Best,
Derek

**Comment by wooorm** [comment]
Fixed in 3.9.1, sorry!
