### ISSUE TITLE
"Native land" may not be a suitable alternative for "motherland"

### ISSUE THREAD

**Issue by diglyt** [retextjs/retext-equality#92]
I don't have a better suggestion, but "native land" feels like a potentially problematic suggestion to be recommending to people whose families may not be from the indigenous peoples of their home country. See https://native-land.ca/

**Comment by wooorm** [comment]
Hi, thanks for helping!

I am not a “native” English speaker so I can’t speak with authority on how English should be used, but in my understanding “fatherland” and “motherland” seem to reference the place where parent(s)/person themselves come from. The word “native”, according to Merriam-Webster:

> 1. belonging to a particular place by birth\
      *a native New Yorker*
> 2. belonging to or associated with one by birth\
      *hailed in his native Sweden as an influential dramatist*

To me it looks like these cases don’t necessarily imply that the person in question is an indigenous person to those territories, but rather that they hail or reside in those places?

Maybe the combination with land is different though? Wouldn’t “indigenous land” better reflect the historical ties?

Note also that, if “native” is not correct, “homeland” is also provided as a suggestion.

**Comment by wooorm** [comment]
@diglyt Any further thoughts?

**Comment by wooorm** [comment]
Closing for now, I’d love to hear others’ opinions tho!
