### ISSUE TITLE
Repo: readme.md example output no longer matches text

### ISSUE THREAD

**Issue by ferdnyc** [retextjs/retext-equality#95]
Commit 1585a36524c9462a355cc45821ccd4e4303d9800 changed the sample prose in the usage example to this sentence:

> `He’s pretty set on beating your butt for sheriff.`

But it didn't adjust the output to match. As a result, the sample output:

> ```
> example.txt
>     1:1-1:4  warning  `His` may be insensitive, use `Their`, `Theirs`, `Them` instead           her-him       retext-equality
>   1:31-1:37  warning  `master` / `slave` may be insensitive, use `primary` / `replica` instead  master-slave  retext-equality
> 
> ⚠ 2 warnings
> ```
> 

contains admonishments about language (`master`, `slave`) that doesn't appear anywhere in the input text.

**Comment by wooorm** [comment]
Thanks!
