### ISSUE TITLE
Don't flag the word `mental` in the phrase "mental health"

### ISSUE THREAD

**Issue by ouroboros8** [retextjs/retext-equality#96]
### Subject of the issue

Currently the word "mental" is flagged as inconsiderate in the context of the phrase "mental health".

### Expected behaviour

When used in the harmless contexts of the phrase "mental health", the word "mental" should not be flagged.

### Actual behaviour

The word "mental" is flagged as inappropriate.

**Comment by ouroboros8** [comment]
I am happy to have a stab at fixing this, but would appreciate some advice on whether this should constitute a new rule or be part of an existing rule :)

**Comment by wooorm** [comment]
We could remove this line:

https://github.com/retextjs/retext-equality/blob/96fe3ecf8710c19666cdc42808fc109b84e0fca2/data/en/ablist.yml#L87

That would drop a couple of cases where `mental` is used as a slur, but `mentally ill`, `mental defective`, and `mental case` are already caught.

**Comment by wooorm** [comment]
There is no support (yet) for warning about a pattern, *unless* it’s also part of a different pattern, so that would be difficult.

**Comment by ouroboros8** [comment]
Ah that's a shame. I think it might be best to leave it in that case. Removing it entirely would lead to phrases like `They're mental.` not being caught, and it's probably preferable to retain false positives than introduce false negatives.

**Comment by wooorm** [comment]
Yeahhhh, true. Unfortunate problem, but I’m not really sure how to fix it 🤷‍♂️

Thanks for mentioning it tho!
